services:

  admin-frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - 8082:8082
    volumes:
      - /app
      - /app/node_modules
    networks:
      - ucomand-network

networks:
  ucomand-network:
    external: true
